# Generated by Django 4.1.2 on 2024-03-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('Algodón', 'Algodón'), ('Poliéster', 'Poliéster'), ('Cuero', 'Cuero'), ('Metálico', 'Metálico')], max_length=30)),
                ('color', models.CharField(choices=[('Negro', 'Negro'), ('Blanco', 'Blanco'), ('Rojo', 'Rojo'), ('Azul', 'Azul'), ('Verde', 'Verde'), ('Rosado', 'Rosado'), ('Morado', 'Morado')], max_length=30)),
                ('talla', models.CharField(choices=[('Pequeño', 'Pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], max_length=30)),
            ],
        ),
    ]
