# Generated by Django 4.1.2 on 2024-03-12 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_collar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collar',
        ),
    ]
