# Generated by Django 4.1.2 on 2024-03-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_collar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collar',
            old_name='talla',
            new_name='size',
        ),
    ]
